
SINGLE_STOCK_TICKERS = ['AAPL','MSFT','AMZN','GOOGL','META','TSLA','JPM']
SECTOR_TICKERS = ['XLK', 'XLY', 'XLC', 'XLI', 'XLF', 'XLE', 'XLB', 'XLV', 'XLU', 'XLP','XLRE']
FI_TICKERS = ['AGG', 'BND', 'JBND']
MARKET_TICKERS = ['SPY', 'QQQ', 'IWM', 'VBR','ITOT']

MISC_TICKERS = []

ALL_TICKERS = SINGLE_STOCK_TICKERS + SECTOR_TICKERS + FI_TICKERS + MARKET_TICKERS + MISC_TICKERS